# Generated by Django 4.2.2 on 2023-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pan', models.CharField(max_length=30)),
                ('tan', models.CharField(max_length=30)),
                ('md', models.CharField(max_length=30)),
                ('desig', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('cnfmPass', models.CharField(max_length=30)),
            ],
        ),
    ]
