# Generated by Django 4.2.2 on 2023-06-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_registration_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='cnfmPass',
            new_name='confirm',
        ),
    ]
