# Generated by Django 4.2.2 on 2023-06-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
