# Generated by Django 4.2.2 on 2023-06-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
