# Generated by Django 4.2.2 on 2023-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0012_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('desig', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('md', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('pan', models.IntegerField(max_length=10)),
                ('tan', models.IntegerField(max_length=30)),
                ('service', models.IntegerField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('confirm', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
