# Generated by Django 4.2.2 on 2023-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='service',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tan',
            field=models.IntegerField(),
        ),
    ]
