# Generated by Django 4.2.2 on 2023-06-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_graphdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphData',
        ),
    ]
