# Generated by Django 4.2.2 on 2023-06-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_grievance_alter_graphdata_graph_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grievance',
        ),
    ]
