# Generated by Django 4.2.2 on 2023-06-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(upload_to='feedback'),
        ),
    ]
