# Generated by Django 4.2.2 on 2023-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_feedback_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(null='True', upload_to='feedback/'),
        ),
    ]
